

Languages = [
                "Python",
                "Java",
                "C++",
                "Алгол",
                "Ассемблер",
                "Бейсик",
                "ДРАКОН",
                "Кобол",
                "Лого",
                "Паскаль",
                "Пифагор",
                "Плэнер",
                "Пролог",
                "Рапира",
                "Ратфор",
                "Рефал",
                "Робик",
                "Сетл",
                "Симула",
                "Снобол",
                "Старсет",
                "C Sharp",
                "Caml",
                "Canny",
                "Carbon",
                "Cat",
                "Ceylon",
                "Chapel",
                "CHILL",
                "Church",
                "Cilk",
                "Clarion",
                "Clean",
                "Clipper",
                "CLIPS",
            ]



